#!/bin/bash

# The intention is to have a script that can run with 
#    curl -s "https://raw.githubusercontent.com/folio-org/platform-erm/master/helper_scripts/setup" | bash
# Which will configure a ux env

mkdir agreements_ux
cd agreements_ux

# Copy the workspace package.json
wget https://raw.githubusercontent.com/folio-org/platform-erm/master/helper_scripts/package.json

git clone git@github.com:folio-org/platform-erm.git
git clone git@github.com:folio-org/ui-agreements.git
git clone git@github.com:folio-org/ui-licenses.git


echo Completed clone and setup
echo cd agreements_ux/platform-erm and run "yarn install" to download deps, then "stripes serve ./stripes.gbv-ki-config.js --hasAllPerms" to start the UI
